# Generated by Django 2.2 on 2019-05-07 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='img',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
